# Usa la imagen oficial de PostgreSQL como base
FROM postgres:15-alpine

# Configura variables de entorno para PostgreSQL (opcional)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=votingapp

# Exponer el puerto de PostgreSQL
EXPOSE 5432

CMD ["postgres"]
